"""Add default value for user role

Revision ID: 631426437dd4
Revises: ac802c7cf908
Create Date: 2025-07-19 20:05:08.730770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '631426437dd4'
down_revision = 'ac802c7cf908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'user', name='role_enum'),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('admin', 'user', name='role_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###
