"""added created-by field in record model

Revision ID: 85dc32ea9532
Revises: 96c1f831df59
Create Date: 2025-07-21 15:03:34.139323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dc32ea9532'
down_revision = '96c1f831df59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_records_created_by_users'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_records_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
