"""add image and video fields to record model

Revision ID: 96c1f831df59
Revises: 6a81cc0c1095
Create Date: 2025-07-21 10:29:23.033338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c1f831df59'
down_revision = '6a81cc0c1095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('videos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('videos')
        batch_op.drop_column('images')

    # ### end Alembic commands ###
